name: PHPStan

on: [push, pull_request]      

jobs: 
  phpstan: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '7.4'
          tools: phpstan, composer:v2
      - name: Clone PocketMine
        uses: actions/checkout@v2
        with: 
          repository: 'pmmp/PocketMine-MP'
          path: 'pocketmine'
          ref: 'master'
          submodules: true
      - run: cd pocketmine
      - name: Install PocketMine Dependencies
        run: composer install --prefer-dist --no-interaction
      - run: cd ..
      - name: Run PHPStan
        run: phpstan analyze --no-progress
