name: PHPStan

on: [push, pull_request]      

jobs: 
  phpstan: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build PHP
        uses: wei/wget@v1
        with:
          args: https://github.com/pmmp/php-build-scripts/raw/stable/compile.sh
      - run: chmod +x compile.sh
      - run: ./compile.sh
      - name: Clone PocketMine
        uses: actions/checkout@v2
        with: 
          repository: 'pmmp/PocketMine-MP'
          path: 'pocketmine'
          ref: 'master'
          submodules: true
      - run: ls
      - name: Install PocketMine Dependencies
        run: composer install --prefer-dist --no-interaction --working-dir=pocketmine
      - name: Run PHPStan
        run: phpstan analyze --no-progress
