name: PHPStan

on: [push, pull_request]      

jobs: 
  phpstan: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download PHP
        uses: wei/curl@master
        with:
          args: -o php.zip '"https://dev.azure.com/pocketmine/a29511ba-1771-4ad2-a606-23c00a4b8b92/_apis/build/builds/348/artifacts?artifactName=Linux&api-version=6.0&%24format=zip"'
      - run: unzip php.zip
      - run: cd php/Linux
      - run: tar -xzvf PHP*.tar.gz
      - run: mb bin ../../
      - name: Clone PocketMine
        uses: actions/checkout@v2
        with:
          repository: 'pmmp/PocketMine-MP'
          path: 'pocketmine'
          ref: 'master'
          submodules: true
      - run: ls
      - name: Install PocketMine Dependencies
        run: composer install --prefer-dist --no-interaction --working-dir=pocketmine
      - name: Run PHPStan
        run: phpstan analyze --no-progress
